permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true
highlighter: rouge

kramdown:
  input: GFM

# 作者信息
author: 
  name: 临水照影的博客 
  email: 4799109@qq.com
  link: http://linshuizhaoying.github.io
  weibo: 不玩
  github: http://github.com/linshuizhaoying

# 站点信息
title: 临水照影的博客 
description: 临水照影的博客
url: http://linshuizhaoying.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7s1say.com1.z0.glb.clouddn.com/avatar639D58E2-E732-4FF9-8E05-724717DFEF1F.png
favicon: http://7s1say.com1.z0.glb.clouddn.com/avatar639D58E2-E732-4FF9-8E05-724717DFEF1F.png

# google analytics 设置
ga:
  id: UA-54767140-1
  url: linshuizhaoying.github.io

# disqus 设置
disqus:
  shortname: linshuizhaoying-zh